ALL=`{ls *.t}

all:V: ${ALL:%.t=%.pdf}

%.ms:D:	%.t
	cat msglobal $prereq | pic | tbl | eqn | 
		troff -mpictures > $target
	chmod +t $target

%.ps:D: %.ms
	lp -dstdout -L < $prereq > $target
	chmod +t $target

# file:/sys/src/cmd/gs/doc/Use.htm
%.pdf:D: %.ps
	ps2pdf < $prereq > $target
	chmod +t $target

%.gif:D:
	togif -d 750 $stem[0-9a-z]*.bit > $target
	chmod +t $target

clean:
	rm -f *.pdf *.ps *.gif *.ms
