ALL=`{ls *.t}

all:V: ${ALL:%.t=%.pdf}

%.ms:D: %.t
	cat msglobal $prereq | pic | tbl | eqn | 
		troff -mpictures > $target

%.ps:D: %.ms
	lp -dstdout < $prereq > $target

%.pdf:D: %.ps
	ps2pdf $prereq > $target

clean:
	rm -f *.pdf *.ps *.ms
